version: "3.9"

services:
  db:
    image: postgres:16
    container_name: movieticket-db
    environment:
      POSTGRES_DB: movieticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../movie-ticket-system
    container_name: movieticket-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/movieticketdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "7070:7070"

  frontend:
    build:
      context: ../movie-ticket-frontend
    container_name: movieticket-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data: